DOCKER_TAG: ""
ENVIRONMENT_NAME: "default"
ENV_CONFIGURATION_TEMPLATE_FILENAME: "environment-configuration-template.json"
ATP_TESTS_GIT_REPO_URL: ""
ATP_TESTS_GIT_REPO_BRANCH: "main"
ATP_TESTS_GIT_TOKEN: "your-token"
ATP_STORAGE_PROVIDER: "minio"
ATP_STORAGE_REGION: ""
ATP_STORAGE_BUCKET: ""
ATP_STORAGE_USERNAME: "storage-access-key"
ATP_STORAGE_PASSWORD: "storage-secret-key"
ATP_STORAGE_SERVER_URL: ""
ATP_STORAGE_SERVER_UI_URL: ""
ATP_REPORT_VIEW_UI_URL: ""
CURRENT_DATE: ""
CURRENT_TIME: ""
ATP_RUNNER_JOB_TTL: "3600"
ATP_RUNNER_JOB_EXIT_STRATEGY: "EXIT_ALWAYS"
DEBUG_MODE: false
TEST_PARAMS: {}
ATP_ENVGENE_CONFIGURATION: {}
ENABLE_JIRA_INTEGRATION: false
ATP_MONITORING_ENABLED: true
EXTRA_VARS: ""
TRIGGER_AUTHOR: ""
# Security Context properties
# enabled is a flag to enable Security Context
SECURITY_CONTEXT_ENABLED: false
# runAsUser is the user ID used to run the container
podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000
containerSecurityContext: {}
affinity: {}
tolerations: []

# Variables for render environment configuration template
CLOUD_PROTOCOL: ""
CLOUD_PUBLIC_HOST: ""
DEFAULT_TENANT_NAME: ""
DEFAULT_TENANT_ADMIN_LOGIN: ""
DEFAULT_TENANT_ADMIN_PASSWORD: ""
CONSUL_PUBLIC_URL: ""
CONSUL_ADMIN_TOKEN: ""
ARGOCD_USER: ""
ARGOCD_PASSWORD: ""
K8S_TOKEN: ""