apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atp3-python-runner.fullname" . }}-cm
data:
  CLOUD_PROTOCOL: {{ .Values.CLOUD_PROTOCOL | default "" | quote }}
  CLOUD_PUBLIC_HOST: {{ .Values.CLOUD_PUBLIC_HOST | default "" | quote }}
  CONSUL_PUBLIC_URL: {{ .Values.CONSUL_PUBLIC_URL | default "" | quote }}
