apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "atp3-python-runner.fullname" . }}
  labels:
    app: {{ include "atp3-python-runner.name" . }}
    metrics-type: atp3-service
spec:
  ttlSecondsAfterFinished: {{ .Values.ATP_RUNNER_JOB_TTL }}

  template:
    metadata:
      labels:
        metrics-type: atp3-service
    spec:
      {{- if .Values.SECURITY_CONTEXT_ENABLED }}
      securityContext:
        {{- include "securityContext.pod" . | nindent 12 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}

      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: atp3-python-runner
          image: '{{ .Values.DOCKER_TAG }}'
          {{- if .Values.SECURITY_CONTEXT_ENABLED }}
          securityContext:
            {{- include "securityContext.container" . | nindent 12 }}
          {{- end }}
          resources:
            requests:
              memory: '{{ .Values.MEMORY_REQUEST }}'
              cpu: '{{ .Values.CPU_REQUEST }}'
            limits:
              memory: '{{ .Values.MEMORY_LIMIT }}'
              cpu: '{{ .Values.CPU_LIMIT }}'
          env:
            - name: ATP_TESTS_GIT_REPO_URL
              value: "{{ .Values.ATP_TESTS_GIT_REPO_URL }}"
            - name: ATP_TESTS_GIT_REPO_BRANCH
              value: "{{ .Values.ATP_TESTS_GIT_REPO_BRANCH }}"
            - name: ENVIRONMENT_NAME
              value: "{{ .Values.ENVIRONMENT_NAME }}"
            - name: ENV_CONFIGURATION_TEMPLATE_FILENAME
              value: {{ .Values.ENV_CONFIGURATION_TEMPLATE_FILENAME | default "environment-configuration-template.json" | quote }}
            - name: ATP_STORAGE_PROVIDER
              value: "{{ .Values.ATP_STORAGE_PROVIDER }}"
            - name: ATP_STORAGE_REGION
              value: "{{ .Values.ATP_STORAGE_REGION }}"
            - name: ATP_STORAGE_SERVER_URL
              value: "{{ .Values.ATP_STORAGE_SERVER_URL }}"
            - name: ATP_STORAGE_SERVER_UI_URL
              value: "{{ .Values.ATP_STORAGE_SERVER_UI_URL }}"
            - name: ATP_REPORT_VIEW_UI_URL
              value: "{{ .Values.ATP_REPORT_VIEW_UI_URL }}"
            - name: ATP_RUNNER_JOB_EXIT_STRATEGY
              value: "{{ .Values.ATP_RUNNER_JOB_EXIT_STRATEGY }}"
            - name: CURRENT_DATE
              value: "{{ .Values.CURRENT_DATE }}"
            - name: CURRENT_TIME
              value: "{{ .Values.CURRENT_TIME }}"
            - name: ATP_STORAGE_BUCKET
              value: "{{ .Values.ATP_STORAGE_BUCKET }}"
            - name: ENABLE_JIRA_INTEGRATION
              value: "{{ .Values.ENABLE_JIRA_INTEGRATION }}"
            - name: ATP_MONITORING_ENABLED
              value: "{{ .Values.ATP_MONITORING_ENABLED }}"
            - name: DEBUG_MODE
              value: "{{ .Values.DEBUG_MODE }}"
            - name: TEST_PARAMS
              value: {{ toJson .Values.TEST_PARAMS | quote }}
            - name: EXTRA_VARS
              value: "{{ .Values.EXTRA_VARS }}"
            - name: TRIGGER_AUTHOR
              value: "{{ .Values.TRIGGER_AUTHOR }}"
            - name: ATP_APPLICATION_VERSION
              value: "{{ .Values.ATP_APPLICATION_VERSION }}"
            - name: ATP_ENVGENE_CONFIGURATION
              valueFrom:
                secretKeyRef:
                  name: {{ include "atp3-python-runner.fullname" . }}-secret
                  key: atpEnvgeneConfiguration
            - name: ATP_TESTS_GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "atp3-python-runner.fullname" . }}-secret
                  key: atpTestsGitToken
            - name: ATP_STORAGE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "atp3-python-runner.fullname" . }}-secret
                  key: atpStorageUsername
            - name: ATP_STORAGE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "atp3-python-runner.fullname" . }}-secret
                  key: atpStoragePassword
            - name: DEFAULT_TENANT_ADMIN_LOGIN
              valueFrom:
                secretKeyRef:
                  name: {{ include "atp3-python-runner.fullname" . }}-secret
                  key: defaultTenantAdminLogin
            - name: DEFAULT_TENANT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "atp3-python-runner.fullname" . }}-secret
                  key: defaultTenantAdminPassword
            - name: DEFAULT_TENANT_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "atp3-python-runner.fullname" . }}-secret
                  key: defaultTenantName
            - name: CONSUL_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "atp3-python-runner.fullname" . }}-secret
                  key: consulAdminToken
            - name: ARGOCD_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                  key: argocdUser
            - name: ARGOCD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                  key: argocdPassword
            - name: K8S_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                  key: k8sToken
          envFrom:
            - configMapRef:
                name: {{ include "atp3-python-runner.fullname" . }}-cm
      restartPolicy: Never
  backoffLimit: 0
