apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atp3-python-runner.fullname" . }}-secret
type: Opaque
data:
  atpTestsGitToken: {{ default "" .Values.ATP_TESTS_GIT_TOKEN | b64enc | quote }}
  atpEnvgeneConfiguration: {{ toJson .Values.ATP_ENVGENE_CONFIGURATION | b64enc | quote }}
  atpStorageUsername: {{ default "" .Values.ATP_STORAGE_USERNAME | b64enc | quote }}
  atpStoragePassword: {{ default "" .Values.ATP_STORAGE_PASSWORD | b64enc | quote }}

  defaultTenantAdminLogin: {{ default "" .Values.DEFAULT_TENANT_ADMIN_LOGIN | b64enc | quote }}
  defaultTenantAdminPassword: {{ default "" .Values.DEFAULT_TENANT_ADMIN_PASSWORD | b64enc | quote }}
  defaultTenantName: {{ default "" .Values.DEFAULT_TENANT_NAME | b64enc | quote }}
  consulAdminToken: {{ default "" .Values.CONSUL_ADMIN_TOKEN | b64enc | quote }}